// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cluster

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/dsql"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/dsql/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/dsql-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Cluster{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetClusterOutput
	resp, err = rm.sdkapi.GetCluster(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetCluster", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if resp.DeletionProtectionEnabled != nil {
		ko.Spec.DeletionProtectionEnabled = resp.DeletionProtectionEnabled
	} else {
		ko.Spec.DeletionProtectionEnabled = nil
	}
	if resp.EncryptionDetails != nil {
		f3 := &svcapitypes.EncryptionDetails{}
		if resp.EncryptionDetails.EncryptionStatus != "" {
			f3.EncryptionStatus = aws.String(string(resp.EncryptionDetails.EncryptionStatus))
		}
		if resp.EncryptionDetails.EncryptionType != "" {
			f3.EncryptionType = aws.String(string(resp.EncryptionDetails.EncryptionType))
		}
		if resp.EncryptionDetails.KmsKeyArn != nil {
			f3.KMSKeyARN = resp.EncryptionDetails.KmsKeyArn
		}
		ko.Status.EncryptionDetails = f3
	} else {
		ko.Status.EncryptionDetails = nil
	}
	if resp.Endpoint != nil {
		ko.Status.Endpoint = resp.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.Identifier != nil {
		ko.Status.Identifier = resp.Identifier
	} else {
		ko.Status.Identifier = nil
	}
	if resp.MultiRegionProperties != nil {
		f6 := &svcapitypes.MultiRegionProperties{}
		if resp.MultiRegionProperties.Clusters != nil {
			f6.Clusters = aws.StringSlice(resp.MultiRegionProperties.Clusters)
		}
		if resp.MultiRegionProperties.WitnessRegion != nil {
			f6.WitnessRegion = resp.MultiRegionProperties.WitnessRegion
		}
		ko.Spec.MultiRegionProperties = f6
	} else {
		ko.Spec.MultiRegionProperties = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Tags)
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)

	if err := setResourcePolicy(ctx, rm, ko); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.Identifier == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetClusterInput, error) {
	res := &svcsdk.GetClusterInput{}

	if r.ko.Status.Identifier != nil {
		res.Identifier = r.ko.Status.Identifier
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateClusterOutput
	_ = resp
	resp, err = rm.sdkapi.CreateCluster(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateCluster", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if resp.DeletionProtectionEnabled != nil {
		ko.Spec.DeletionProtectionEnabled = resp.DeletionProtectionEnabled
	} else {
		ko.Spec.DeletionProtectionEnabled = nil
	}
	if resp.EncryptionDetails != nil {
		f3 := &svcapitypes.EncryptionDetails{}
		if resp.EncryptionDetails.EncryptionStatus != "" {
			f3.EncryptionStatus = aws.String(string(resp.EncryptionDetails.EncryptionStatus))
		}
		if resp.EncryptionDetails.EncryptionType != "" {
			f3.EncryptionType = aws.String(string(resp.EncryptionDetails.EncryptionType))
		}
		if resp.EncryptionDetails.KmsKeyArn != nil {
			f3.KMSKeyARN = resp.EncryptionDetails.KmsKeyArn
		}
		ko.Status.EncryptionDetails = f3
	} else {
		ko.Status.EncryptionDetails = nil
	}
	if resp.Endpoint != nil {
		ko.Status.Endpoint = resp.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.Identifier != nil {
		ko.Status.Identifier = resp.Identifier
	} else {
		ko.Status.Identifier = nil
	}
	if resp.MultiRegionProperties != nil {
		f6 := &svcapitypes.MultiRegionProperties{}
		if resp.MultiRegionProperties.Clusters != nil {
			f6.Clusters = aws.StringSlice(resp.MultiRegionProperties.Clusters)
		}
		if resp.MultiRegionProperties.WitnessRegion != nil {
			f6.WitnessRegion = resp.MultiRegionProperties.WitnessRegion
		}
		ko.Spec.MultiRegionProperties = f6
	} else {
		ko.Spec.MultiRegionProperties = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateClusterInput, error) {
	res := &svcsdk.CreateClusterInput{}

	if r.ko.Spec.DeletionProtectionEnabled != nil {
		res.DeletionProtectionEnabled = r.ko.Spec.DeletionProtectionEnabled
	}
	if r.ko.Spec.KMSEncryptionKey != nil {
		res.KmsEncryptionKey = r.ko.Spec.KMSEncryptionKey
	}
	if r.ko.Spec.MultiRegionProperties != nil {
		f3 := &svcsdktypes.MultiRegionProperties{}
		if r.ko.Spec.MultiRegionProperties.Clusters != nil {
			f3.Clusters = aws.ToStringSlice(r.ko.Spec.MultiRegionProperties.Clusters)
		}
		if r.ko.Spec.MultiRegionProperties.WitnessRegion != nil {
			f3.WitnessRegion = r.ko.Spec.MultiRegionProperties.WitnessRegion
		}
		res.MultiRegionProperties = f3
	}
	if r.ko.Spec.Policy != nil {
		res.Policy = r.ko.Spec.Policy
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()

	skipUpdate, err := customUpdate(ctx, rm, desired, latest, delta)
	if err != nil {
		return nil, err
	}
	if skipUpdate {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	// multiRegionProperties is only mutable in PENDING_SETUP; DSQL rejects an
	// UpdateCluster carrying it otherwise, so drop it for other states.
	if latest.ko.Status.Status == nil || *latest.ko.Status.Status != "PENDING_SETUP" {
		input.MultiRegionProperties = nil
	}

	var resp *svcsdk.UpdateClusterOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateCluster(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateCluster", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.Arn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.Arn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if resp.Identifier != nil {
		ko.Status.Identifier = resp.Identifier
	} else {
		ko.Status.Identifier = nil
	}
	if resp.Status != "" {
		ko.Status.Status = aws.String(string(resp.Status))
	} else {
		ko.Status.Status = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateClusterInput, error) {
	res := &svcsdk.UpdateClusterInput{}

	if r.ko.Spec.DeletionProtectionEnabled != nil {
		res.DeletionProtectionEnabled = r.ko.Spec.DeletionProtectionEnabled
	}
	if r.ko.Status.Identifier != nil {
		res.Identifier = r.ko.Status.Identifier
	}
	if r.ko.Spec.KMSEncryptionKey != nil {
		res.KmsEncryptionKey = r.ko.Spec.KMSEncryptionKey
	}
	if r.ko.Spec.MultiRegionProperties != nil {
		f4 := &svcsdktypes.MultiRegionProperties{}
		if r.ko.Spec.MultiRegionProperties.Clusters != nil {
			f4.Clusters = aws.ToStringSlice(r.ko.Spec.MultiRegionProperties.Clusters)
		}
		if r.ko.Spec.MultiRegionProperties.WitnessRegion != nil {
			f4.WitnessRegion = r.ko.Spec.MultiRegionProperties.WitnessRegion
		}
		res.MultiRegionProperties = f4
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteClusterOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteCluster(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteCluster", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteClusterInput, error) {
	res := &svcsdk.DeleteClusterInput{}

	if r.ko.Status.Identifier != nil {
		res.Identifier = r.ko.Status.Identifier
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Cluster,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
