// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterSpec defines the desired state of Cluster.
type ClusterSpec struct {

	// If enabled, you can't delete your cluster. You must first disable this property
	// before you can delete your cluster.
	DeletionProtectionEnabled *bool `json:"deletionProtectionEnabled,omitempty"`
	// The KMS key that encrypts and protects the data on your cluster. You can
	// specify the ARN, ID, or alias of an existing key or have Amazon Web Services
	// create a default key for you.
	//
	// Regex Pattern: `^[a-zA-Z0-9:/_-]+$`
	KMSEncryptionKey    *string                                  `json:"kmsEncryptionKey,omitempty"`
	KMSEncryptionKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsEncryptionKeyRef,omitempty"`
	// The configuration settings when creating a multi-Region cluster, including
	// the witness region and linked cluster properties.
	MultiRegionProperties *MultiRegionProperties `json:"multiRegionProperties,omitempty"`
	// An optional resource-based policy document in JSON format that defines access
	// permissions for the cluster.
	Policy *string `json:"policy,omitempty"`
	// A map of key and value pairs to use to tag your cluster.
	Tags map[string]*string `json:"tags,omitempty"`
}

// ClusterStatus defines the observed state of Cluster
type ClusterStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The time of when created the cluster.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The encryption configuration for the cluster that was specified during the
	// creation process, including the KMS key identifier and encryption state.
	// +kubebuilder:validation:Optional
	EncryptionDetails *EncryptionDetails `json:"encryptionDetails,omitempty"`
	// The connection endpoint for the created cluster.
	//
	// Regex Pattern: `^[a-zA-Z0-9.-]+$`
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty"`
	// The ID of the created cluster.
	//
	// Regex Pattern: `^[a-z0-9]{26}$`
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty"`
	// The status of the created cluster.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// Cluster is the Schema for the Clusters API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ENDPOINT",type=string,priority=0,JSONPath=`.status.endpoint`
// +kubebuilder:printcolumn:name="ID",type=string,priority=0,JSONPath=`.status.identifier`
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.status`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterSpec   `json:"spec,omitempty"`
	Status            ClusterStatus `json:"status,omitempty"`
}

// ClusterList contains a list of Cluster
// +kubebuilder:object:root=true
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
