// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ClusterStatus_SDK string

const (
	ClusterStatus_SDK_ACTIVE         ClusterStatus_SDK = "ACTIVE"
	ClusterStatus_SDK_CREATING       ClusterStatus_SDK = "CREATING"
	ClusterStatus_SDK_DELETED        ClusterStatus_SDK = "DELETED"
	ClusterStatus_SDK_DELETING       ClusterStatus_SDK = "DELETING"
	ClusterStatus_SDK_FAILED         ClusterStatus_SDK = "FAILED"
	ClusterStatus_SDK_IDLE           ClusterStatus_SDK = "IDLE"
	ClusterStatus_SDK_INACTIVE       ClusterStatus_SDK = "INACTIVE"
	ClusterStatus_SDK_PENDING_DELETE ClusterStatus_SDK = "PENDING_DELETE"
	ClusterStatus_SDK_PENDING_SETUP  ClusterStatus_SDK = "PENDING_SETUP"
	ClusterStatus_SDK_UPDATING       ClusterStatus_SDK = "UPDATING"
)

type EncryptionStatus string

const (
	EncryptionStatus_ENABLED              EncryptionStatus = "ENABLED"
	EncryptionStatus_ENABLING             EncryptionStatus = "ENABLING"
	EncryptionStatus_KMS_KEY_INACCESSIBLE EncryptionStatus = "KMS_KEY_INACCESSIBLE"
	EncryptionStatus_UPDATING             EncryptionStatus = "UPDATING"
)

type EncryptionType string

const (
	EncryptionType_AWS_OWNED_KMS_KEY        EncryptionType = "AWS_OWNED_KMS_KEY"
	EncryptionType_CUSTOMER_MANAGED_KMS_KEY EncryptionType = "CUSTOMER_MANAGED_KMS_KEY"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_cannotParse               ValidationExceptionReason = "cannotParse"
	ValidationExceptionReason_deletionProtectionEnabled ValidationExceptionReason = "deletionProtectionEnabled"
	ValidationExceptionReason_fieldValidationFailed     ValidationExceptionReason = "fieldValidationFailed"
	ValidationExceptionReason_other                     ValidationExceptionReason = "other"
	ValidationExceptionReason_unknownOperation          ValidationExceptionReason = "unknownOperation"
)
