// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// A summary of the properties of a cluster.
type ClusterSummary struct {
	// The Amazon Resource Name of the cluster.
	ARN *string `json:"arn,omitempty"`
	// The ID of the cluster.
	Identifier *string `json:"identifier,omitempty"`
}

// Configuration details about encryption for the cluster including the KMS
// key ARN, encryption type, and encryption status.
type EncryptionDetails struct {
	EncryptionStatus *string `json:"encryptionStatus,omitempty"`
	EncryptionType   *string `json:"encryptionType,omitempty"`
	KMSKeyARN        *string `json:"kmsKeyARN,omitempty"`
}

// Defines the structure for multi-Region cluster configurations, containing
// the witness region and linked cluster settings.
type MultiRegionProperties struct {
	// A list of the Amazon Resource Names of the cluster.
	Clusters []*string `json:"clusters,omitempty"`
	// Region name.
	WitnessRegion *string `json:"witnessRegion,omitempty"`
}
